//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class universityEntities : DbContext
{
    public universityEntities()
        : base("name=universityEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<career> career { get; set; }
    public virtual DbSet<course> course { get; set; }
    public virtual DbSet<incription_course> incription_course { get; set; }
    public virtual DbSet<result_state> result_state { get; set; }
    public virtual DbSet<teacher_course_assignement> teacher_course_assignement { get; set; }
    public virtual DbSet<user_type> user_type { get; set; }
    public virtual DbSet<usuario> usuario { get; set; }
    public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
}
