//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class career
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public career()
    {
        this.course = new HashSet<course>();
        this.usuario = new HashSet<usuario>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public string description { get; set; }
    public bool is_enabled { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<course> course { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<usuario> usuario { get; set; }
}

public partial class course
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public course()
    {
        this.teacher_course_assignement = new HashSet<teacher_course_assignement>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public bool is_enabled { get; set; }
    public int id_career { get; set; }

    public virtual career career { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<teacher_course_assignement> teacher_course_assignement { get; set; }
}

public partial class database_firewall_rules
{
    public int id { get; set; }
    public string name { get; set; }
    public string start_ip_address { get; set; }
    public string end_ip_address { get; set; }
    public System.DateTime create_date { get; set; }
    public System.DateTime modify_date { get; set; }
}

public partial class incription_course
{
    public int id { get; set; }
    public int note { get; set; }
    public string observation { get; set; }
    public int id_student { get; set; }
    public int id_course { get; set; }
    public int id_state { get; set; }

    public virtual usuario usuario { get; set; }
    public virtual result_state result_state { get; set; }
    public virtual teacher_course_assignement teacher_course_assignement { get; set; }
}

public partial class result_state
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public result_state()
    {
        this.incription_course = new HashSet<incription_course>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public string description { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<incription_course> incription_course { get; set; }
}

public partial class teacher_course_assignement
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public teacher_course_assignement()
    {
        this.incription_course = new HashSet<incription_course>();
    }

    public int id_assign { get; set; }
    public int id_course { get; set; }
    public int id_teacher { get; set; }

    public virtual course course { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<incription_course> incription_course { get; set; }
    public virtual usuario usuario { get; set; }
}

public partial class user_type
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public user_type()
    {
        this.usuario = new HashSet<usuario>();
    }

    public int id { get; set; }
    public string name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<usuario> usuario { get; set; }
}

public partial class usuario
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public usuario()
    {
        this.incription_course = new HashSet<incription_course>();
        this.teacher_course_assignement = new HashSet<teacher_course_assignement>();
    }

    public int id { get; set; }
    public string complete_name { get; set; }
    public long dpi { get; set; }
    public string email { get; set; }
    public string password { get; set; }
    public string address { get; set; }
    public System.DateTime birth_date { get; set; }
    public Nullable<long> phone { get; set; }
    public Nullable<long> cell_phone { get; set; }
    public bool is_enabled { get; set; }
    public int id_type { get; set; }
    public Nullable<int> id_career { get; set; }

    public virtual career career { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<incription_course> incription_course { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<teacher_course_assignement> teacher_course_assignement { get; set; }
    public virtual user_type user_type { get; set; }
}
